# Generated by Django 4.1.4 on 2024-02-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='date_earned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='graduation_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='institution_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
