# Generated by Django 4.1.4 on 2024-02-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_personalinformation_date_earned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='language_proficiency',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='your_role',
        ),
    ]
