# Generated by Django 4.1.4 on 2024-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_personalinformation_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='date_earned',
            field=models.DateField(blank=True, default='2001-01-01', null=True),
        ),
    ]
