# Generated by Django 4.1.4 on 2024-02-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_personalinformation_date_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='awards_honors',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='interests_hobbies',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='volunteer_experience',
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_earned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
