# Generated by Django 4.1.4 on 2024-02-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_personalinformation_awards_honors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='degree_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='field_of_study_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='gpa_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='graduation_year_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='institution_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='institution_location_1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
