# Generated by Django 4.1.4 on 2024-02-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_personalinformation_degree_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='certification_name_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='company_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='company_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_earned_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='employment_dates_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='employment_dates_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='issuing_organization_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='job_title_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='job_title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='project_description_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='project_description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='project_title_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='project_title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='project_url_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='project_url_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='responsibilities_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='responsibilities_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='technologies_used_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='technologies_used_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='work_location_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='work_location_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
