# Generated by Django 4.2.10 on 2024-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_personalinformation_certification_name_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='gpa_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
