# Generated by Django 4.2.10 on 2024-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_personalinformation_gpa_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='graduation_year_1',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
